# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ChatterKB
email: hello@chatterkb.com
logo: "/assets/images/chatterkb-logo-ex.png"
description: >- # this means to ignore newlines until "baseurl:"
  Effortlessly chat with your files, using AI, and create actionable dashboards.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chatterkb.com" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: G-SS1WEGKVQN
google_ads: AW-16845040931
# twitter_username: frank_fdez
# github_username:  jekyll


company_name: "Beatspoken LLC."
sign_in_url: "https://localhost:3000/auth/login"
pricing_url: "https://app.chatterkb.com/checkout/plans"
pricing_url_yearly: "https://app.chatterkb.com/checkout/yearly"
signup_url: "https://localhost:3000/auth/signup"

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin

sass:
    sass_dir: _sass
    quiet_deps: true
    
defaults:
   -
    scope:
      path: "" # Applies to all posts and pages
    values:
      image: ./assets/images/ckb-card.png
   -
    scope:
      type: workflow_library
    values:
      order: 1000
      
# header_pages:
#   - pager-1.markdown
#   - about.markdown

collections:
  workflow_library:
    output: true
    permalink: /workflow-library/:name/

    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
